### ISSUE TITLE
Allow VPs to manually enter electee uniqnames into electee groups.

### ISSUE THREAD

**Issue by mrealm** [tbpmig/mig-website#128]
Allow VPs to manually enter electee uniqnames into electee groups. (Ideally, when a uniqname is added to a group, the list of the left should remove that electee or denote that s/he has been assigned to make it easy to see if someone has been missed.)

Current manual (Drag and drop) system is impractical for 100 electees.

**Comment by mikehand** [comment]
It seems like at least part of the issue here was that the electee groups were first generated elsewhere and then the goal was to copy them into the website later. Would this be solved by having the group assignment be done here in the first place?

**Comment by mikehand** [comment]
To play devil's advocate, why is creating them in a spreadsheet necessary? It seems like it's just an extra step put in the middle when they have to be loaded onto the website anyways.

>
@domansyl: 
So what happens is the VP makes them on like an excel sheet. And while its fine to drag the electees into their team's box, when you have 60+ electees the page is huge and you have to keep scrolling and it takes longer than if you could just drop all their uniqnames into the box like you do on MCommunity. I don't think creating the teams on the website is really necessary. Does that make sense?

>>
@mrealm: 
Sylvia,

 Do you remember what the specific issue was here? I'm not sure if Mike's proposed fix will address this. It might, but I don't recall exactly what the issue was.

-M

**Comment by domansyl** [comment]
Because that's, at least for me, how I made them from the results of the
electeharmony form.

On Thu, Jan 15, 2015 at 6:43 PM, mikehand <notifications@github.com> wrote:

> To play devil's advocate, why is creating them in a spreadsheet necessary?
> It seems like it's just an extra step put in the middle when they have to
> be loaded onto the website anyways.
>
> @domansyl <https://github.com/domansyl>:
> So what happens is the VP makes them on like an excel sheet. And while its
> fine to drag the electees into their team's box, when you have 60+ electees
> the page is huge and you have to keep scrolling and it takes longer than if
> you could just drop all their uniqnames into the box like you do on
> MCommunity. I don't think creating the teams on the website is really
> necessary. Does that make sense?
>
> @mrealm <https://github.com/mrealm>:
> Sylvia,
>
>  Do you remember what the specific issue was here? I'm not sure if Mike's
> proposed fix will address this. It might, but I don't recall exactly what
> the issue was.
>
> -M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tbpmig/mig-website/issues/128#issuecomment-70184461>.
>



-- 
Sylvia Domanico
B.S.E. Nuclear Engineering & Radiological Sciences '15
University of Michigan, Ann Arbor
248-219-5717  |   domansyl@umich.edu
