### ISSUE TITLE
Let people submit non-TBP announcements for the bottom of the weekly announcements and for the bottom of general meeting agendas

### ISSUE THREAD

**Issue by mrealm** [tbpmig/mig-website#22]
see the title.

**Comment by mikehand** [comment]
Is this still actually desired? Given the volume of announcements, this would just be clutter IMHO

**Comment by mikehand** [comment]
Per discussion at officer meeting last week, I think this is best left up to the Publicity+Corporate Officers' discretion to be done manually. Submit a new bug if the issue is ever re-opened.
![image](http://i.imgur.com/64RYk.gif)

**Comment by kylelady** [comment]
My primary concern with that is that we'll end up with inconsistent
formatting in the shipped announcements due to people's general inability
to copy/paste successfully. I don't think we should open it up for anyone
can submit, but, if it doesn't exist already, I think there's value to
letting officers or perhaps just PR/CRO submit announcements such that
everything gets formatted together when the announcements are generated.
